railsdemo/config/routes.rb
Railsdemo::Application.routes.draw do
  
  resources :newapps

  resources :zombies

    root :to => "demo#index"

    match ':controller(/:action(/:id))(.:format)'
end

railsdemo/app/models/newapp.rb
class Newapp < ActiveRecord::Base
  attr_accessible :data, :id, :name, :value
end

railsdemo/app/models/notable.rb
class Notable < ActiveRecord::Base
  # attr_accessible :title, :body
end

railsdemo/app/models/page.rb
class Page < ActiveRecord::Base
  
  attr_accessible :page_number, :page_quality, :created_at
  
  belongs_to :subject
  #has_many :sections
  has_and_belongs_to_many :users

  # attr_accessible :title, :body
end

railsdemo/app/models/subject.rb
class Subject < ActiveRecord::Base
  
  attr_accessible :sub_first_name, :sub_last_name, :created_at, :updated_at
  has_many :pages
  # attr_accessible :title, :body
end

railsdemo/app/models/user.rb
class User < ActiveRecord::Base

	has_and_belongs_to_many :pages
  # attr_accessible :title, :body
end

railsdemo/app/models/zombie.rb
class Zombie < ActiveRecord::Base
  attr_accessible :age, :bio, :name
end

railsdemo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

railsdemo/app/controllers/demo_controller.rb
class DemoController < ApplicationController
  
  layout 'admin'

  def index
  	#redirect_to(:action => 'other_hello')
  end

  def hello
  	#render(:text => 'Hello Everyone!')
  	#redirect_to('http://www.google.com')
  	@array = [1,2,3,4,5]
  	@id = params[:id]
  	@page = params[:page]
  end
  	
  def other_hello
  	render(:text => 'Hello Everyone!')
  end	

  def javascript
    
  end  
end

railsdemo/app/controllers/newapps_controller.rb
class NewappsController < ApplicationController
  # GET /newapps
  # GET /newapps.json
  def index
    @newapps = Newapp.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @newapps }
    end
  end

  # GET /newapps/1
  # GET /newapps/1.json
  def show
    @newapp = Newapp.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @newapp }
    end
  end

  # GET /newapps/new
  # GET /newapps/new.json
  def new
    @newapp = Newapp.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @newapp }
    end
  end

  # GET /newapps/1/edit
  def edit
    @newapp = Newapp.find(params[:id])
  end

  # POST /newapps
  # POST /newapps.json
  def create
    @newapp = Newapp.new(params[:newapp])

    respond_to do |format|
      if @newapp.save
        format.html { redirect_to @newapp, notice: 'Newapp was successfully created.' }
        format.json { render json: @newapp, status: :created, location: @newapp }
      else
        format.html { render action: "new" }
        format.json { render json: @newapp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /newapps/1
  # PUT /newapps/1.json
  def update
    @newapp = Newapp.find(params[:id])

    respond_to do |format|
      if @newapp.update_attributes(params[:newapp])
        format.html { redirect_to @newapp, notice: 'Newapp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @newapp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newapps/1
  # DELETE /newapps/1.json
  def destroy
    @newapp = Newapp.find(params[:id])
    @newapp.destroy

    respond_to do |format|
      format.html { redirect_to newapps_url }
      format.json { head :no_content }
    end
  end
end

railsdemo/app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

railsdemo/app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  layout 'admin'

  def index
    list
    render('list')
  end	

  def list
    #Subject.all
    @subjects = Subject.order("subjects.id ASC")
    flash[:notice] = "List of Subjects"
  end	

  def show
  	@subject = Subject.find(params[:id]) 
  end	

  def new
  	@subject = Subject.new
  end	

  def create
  	#Instantiate a new object using form parameters
  	@subject = Subject.new(params[:subject])
  	#save the eobject
  	if @subject.save
  	  #if save succeeds, redirect to the list action.
      flash[:notice] = "Subject Created"
  	  redirect_to(:action => 'list')
  	else  
  	  # if save fails, redisplay the form so user can fix problems
  	  render('new')
  	end  
  end	
 
  def edit
    @subject = Subject.find(params[:id])
  end  

  def update
    #Find object using form parameters
    @subject = Subject.find(params[:id])
    #update the object
    if @subject.update_attributes(params[:subject])
      #if update succeeds, redirect to the list action.
      flash[:notice] = "Subject Updated"
      redirect_to(:action => 'show', :id => @subject.id)
    else  
      # if save fails, redisplay the form so user can fix problems
      render('edit')
    end    
  end  

  def delete
    @subject = Subject.find(params[:id])
  end
  
  def destroy
    @subject = Subject.find(params[:id])
    flash[:notice] = "Subject destroyed"
    @subject.destroy
    redirect_to(:action => 'list')
  end  
end

railsdemo/app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  # Comments are black
  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @zombies }
    end
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
    @zombie = Zombie.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @zombie }
    end
  end

  # GET /zombies/new
  # GET /zombies/new.json
  def new
    @zombie = Zombie.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @zombie }
    end
  end

  # GET /zombies/1/edit
  def edit
    @zombie = Zombie.find(params[:id])
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(params[:zombie])

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render json: @zombie, status: :created, location: @zombie }
      else
        format.html { render action: "new" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /zombies/1
  # PUT /zombies/1.json
  def update
    @zombie = Zombie.find(params[:id])

    respond_to do |format|
      if @zombie.update_attributes(params[:zombie])
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end
  
  #comments are black in color under this color scheme.
  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie = Zombie.find(params[:id])
    @zombie.destroy

    respond_to do |format|
      format.html { redirect_to zombies_url }
      format.json { head :no_content }
    end
  end
end

railsdemo/app/helpers/application_helper.rb
module ApplicationHelper
end

railsdemo/app/helpers/demo_helper.rb
module DemoHelper
end

railsdemo/app/helpers/newapps_helper.rb
module NewappsHelper
end

railsdemo/app/helpers/pages_helper.rb
module PagesHelper
end

railsdemo/app/helpers/subjects_helper.rb
module SubjectsHelper
end

railsdemo/app/helpers/zombies_helper.rb
module ZombiesHelper
end

railsdemo/app/views/demo/hello.html.erb
<h1>Demo#Hello</h1>
<p>Finally!!! Hello world !!!</p>

ID: <%= @id %><br />
Next Page: <%= @page.to_i + 1 %><br />

<%= 1 + 1 %>

<% 3.times do%>
  value: <%= 'xxx' %>
<% end %>

<% @array.each do |n|%>
  value: <%= n %><br />
<% end %> 

<%= link_to("My first link", {:action => 'index'}) %> 

railsdemo/app/views/demo/index.html.erb
<h1>Demo#index</h1>
<p>Finally!!! Hello from the index page !!!</p>

<%= link_to("go back", {:action => 'hello', :id => 20, :page => 5}) %>

railsdemo/app/views/demo/javascript.html.erb
<%= link_to('Roar', :onclick => "jsRoar(); return true;") %>

# <%= javascript_tag("jsRoar();") %>
# <%= javascript_tag("alert('Hello!');") %>

railsdemo/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple CMS| <%= @page_title || 'Admin Area' %></title>
  <%= stylesheet_link_tag('public','admin', :media => "all") %>
  <%= javascript_include_tag "application2" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<footer>
	<p> @example.com/ Abhishak Kapoor</p>
</footer>

</body>
</html>

railsdemo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsdemo(application layout)</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

railsdemo/app/views/newapps/_form.html.erb
<%= form_for(@newapp) do |f| %>
  <% if @newapp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newapp.errors.count, "error") %> prohibited this newapp from being saved:</h2>

      <ul>
      <% @newapp.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_field :data %>
  </div>
  <div class="field">
    <%= f.label :id %><br />
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railsdemo/app/views/newapps/edit.html.erb
<h1>Editing newapp</h1>

<%= render 'form' %>

<%= link_to 'Show', @newapp %> |
<%= link_to 'Back', newapps_path %>

railsdemo/app/views/newapps/index.html.erb
<h1>Listing newapps</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Data</th>
    <th>Id</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @newapps.each do |newapp| %>
  <tr>
    <td><%= newapp.name %></td>
    <td><%= newapp.data %></td>
    <td><%= newapp.id %></td>
    <td><%= newapp.value %></td>
    <td><%= link_to 'Show', newapp %></td>
    <td><%= link_to 'Edit', edit_newapp_path(newapp) %></td>
    <td><%= link_to 'Destroy', newapp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Newapp', new_newapp_path %>

railsdemo/app/views/newapps/new.html.erb
<h1>New newapp</h1>

<%= render 'form' %>

<%= link_to 'Back', newapps_path %>

railsdemo/app/views/newapps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @newapp.name %>
</p>

<p>
  <b>Data:</b>
  <%= @newapp.data %>
</p>

<p>
  <b>Id:</b>
  <%= @newapp.id %>
</p>

<p>
  <b>Value:</b>
  <%= @newapp.value %>
</p>


<%= link_to 'Edit', edit_newapp_path(@newapp) %> |
<%= link_to 'Back', newapps_path %>

railsdemo/app/views/subjects/delete.html.erb
<%= link_to("<<back to list", {:action => 'list'}) %>

<h2> Delete Subject </h2>
<h3> Press 'Delete Subject' button to delete this subject </h3>

<%= form_for(:subject, :url => {:action => 'destroy', :id => @subject.id}) do |f| %>
first name: <%= f.text_field(:sub_first_name) %><br /><br />
last name:  <%= f.text_field(:sub_last_name) %><br /><br />
created at: <%= f.text_field(:created_at) %><br /><br />
            <%= submit_tag("Delete Subject") %>
<% end %>

railsdemo/app/views/subjects/edit.html.erb
<%= form_for(:subject, :url => {:action => 'update', :id => @subject.id}) do |f| %>
first name: <%= f.text_field(:sub_first_name) %><br /><br />
last name:   <%= f.text_field(:sub_last_name) %><br /><br />
created at: <%= f.text_field(:created_at) %><br /><br />
            <%= submit_tag("Update Subject") %>
<% end %>

railsdemo/app/views/subjects/list.html.erb
 Notice: <%= flash[:notice] %><br/><br/>

<%= link_to("Add a new subject", {:action => 'new'}) %>
<table>
	<tr>
		<th>id</th>
		<th>sub_first_name</th>
		<th>Actions</th>
    </tr>
    <% @subjects.each do |subject|%>
    <tr>
    	<td><%= subject.id %></td>
    	<td><%= subject.sub_first_name %></td>
    	<td><%= link_to("Show", {:action => 'show', :id => subject.id}) %>
    		<%= link_to("Edit", {:action => 'edit', :id =>subject.id}) %>
    		<%= link_to("Delete", {:action => 'delete', :id => subject.id}) %>
    	</td>
    </tr>
    <% end %>
</table>

railsdemo/app/views/subjects/new.html.erb
<%= form_for(:subject, :url => {:action => 'create'}) do |f| %>
first name: <%= f.text_field(:sub_first_name) %><br /><br />
last name:   <%= f.text_field(:sub_last_name) %><br /><br />
created at: <%= f.text_field(:created_at) %><br /><br />
            <%= submit_tag("Create Subject") %><br/><br/>
<% end %>

<%= link_to("<< Back to list", {:action => 'list'}) %>

railsdemo/app/views/subjects/show.html.erb
<%= link_to("<<back to list", {:action => 'list'}) %>

<table>
	<tr>
		<th>id</th>
		<th>created_at</th>
		<th>updated_at</th>
		<th>sub_first_name</th>
		<th>sub_last_name</th>
    </tr>
    <tr>
    	<td><%= @subject.id %></td>
    	<td><%= @subject.created_at %></td>
    	<td><%= @subject.updated_at %></td>
    	<td><%= @subject.sub_first_name %></td>
    	<td><%= @subject.sub_last_name %></td>
    </tr>
</table>

railsdemo/app/views/zombies/_form.html.erb
<%= form_for(@zombie) do |f| %>
  <% if @zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% @zombie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railsdemo/app/views/zombies/edit.html.erb
<h1>Editing zombie</h1>

<%= render 'form' %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

railsdemo/app/views/zombies/index.html.erb
<h1>Listing zombies</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Bio</th>
    <th>Age</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>

<% @zombies.each do |zombie| %>
  <tr>
    <td><%= zombie.name %></td>
    <td><%= zombie.bio %></td>
    <td><%= zombie.age %></td>
    <td><%= link_to 'Show', zombie %></td>
    <td><%= link_to 'Edit', edit_zombie_path(zombie) %></td>
    <td><%= link_to 'Destroy', zombie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Zombie', new_zombie_path %>

railsdemo/app/views/zombies/new.html.erb
<h1>New zombie</h1>

<%= render 'form' %>

<%= link_to 'Back', zombies_path %>

railsdemo/app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @zombie.name %>
</p>

<p>
  <b>Bio:</b>
  <%= @zombie.bio %>
</p>

<p>
  <b>Age:</b>
  <%= @zombie.age %>
</p>


<%= link_to 'Edit', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>